#!/bin/sh /etc/rc.common

START=99
STOP=01
USE_PROCD=1
DEPEND=fstab,mcu_update

BIN_PATH=/usr/bin
MASTER_SERVER=master-server
AUDIO_SERVER=audio-server
WIFI_SERVER=wifi-server
APP_SERVER=app-server
DISPLAY_SERVER=display-server
UPGRADE_SERVER=upgrade-server
WEB_SERVER=web-server
MONITOR=Monitor

APP_LIST="$BIN_PATH/$MASTER_SERVER $BIN_PATH/$AUDIO_SERVER $BIN_PATH/$WIFI_SERVER \
          $BIN_PATH/$APP_SERVER $BIN_PATH/$DISPLAY_SERVER $BIN_PATH/$UPGRADE_SERVER \
          $BIN_PATH/$WEB_SERVER $BIN_PATH/$MONITOR"

USER_DATA_DIR=/mnt/UDISK
DELAY_IMAGE_VIDEO_DIR=$USER_DATA_DIR/creality/userdata/delay_image/video
LOG_DIR=$USER_DATA_DIR/creality/userdata/log
FRONTEND_DOWNLOADS_DIR=/usr/share/frontend/downloads
HUMBNAIL_DIR=$USER_DATA_DIR/creality/local_gcode/humbnail
ORIGINAL_DIR=/tmp/creality/original
DEFDATA_DIR=/etc/sysConfig/defData

create_dirs() {

    [ -d $FRONTEND_DOWNLOADS_DIR ] ||  mkdir -p $FRONTEND_DOWNLOADS_DIR
    [ -d $HUMBNAIL_DIR ] || mkdir -p $HUMBNAIL_DIR
    [ -d $ORIGINAL_DIR ] || mkdir -p $ORIGINAL_DIR
    [ -d $DELAY_IMAGE_VIDEO_DIR ] || mkdir -p $DELAY_IMAGE_VIDEO_DIR
    [ -d $FRONTEND_DOWNLOADS_DIR -a -d $HUMBNAIL_DIR -a -d $ORIGINAL_DIR -a -d $DEFDATA_DIR ]\
         && { ln -sf $ORIGINAL_DIR $FRONTEND_DOWNLOADS_DIR; ln -sf $HUMBNAIL_DIR $FRONTEND_DOWNLOADS_DIR;\
         ln -sf $DEFDATA_DIR $FRONTEND_DOWNLOADS_DIR; ln -sf $DELAY_IMAGE_VIDEO_DIR $FRONTEND_DOWNLOADS_DIR;}

}

start_app() {
    local app=$1

    procd_open_instance
    # For debug
    # procd_set_param limits core="unlimited"
    procd_set_param env HOME=/root
    procd_set_param command $app
    procd_close_instance
}

start_apps() {
    for app in $APP_LIST
    do
        [ -x $app ] && start_app $app
    done
}

stop_apps() {
    for app in $APP_LIST
    do
        killall -9 $app
    done
}

start_service() {
    create_dirs

    [ -e /tmp/.stress_test ] && {
        [ -x /usr/bin/factory_stress_test.sh ] && factory_stress_test.sh &
        touch /tmp/load_done
        exit 0
    }

    start_apps
}

stop_service() {
    stop_apps
}
