#!/bin/sh /etc/rc.common

START=15
STOP=90
USE_PROCD=1
DEPEND=fstab
PROG=/usr/bin/device_manager

start_service() {
    procd_open_instance
    procd_set_param command $PROG
    procd_close_instance
}
