#!/bin/sh /etc/rc.common

START=99
STOP=90
USE_PROCD=1
DEPEND=fstab
PROG=/usr/bin/mdns

SN=`get_sn_mac.sh sn`
HOSTNAME=`hostname`

start_service() {
    procd_open_instance
    procd_set_param command $PROG
    procd_append_param command --service _Creality-$SN._udp.local --port 5353 --hostname $HOSTNAME
    # For debug
    #procd_set_param stdout 1
    #procd_set_param stderr 1
    procd_close_instance
}
