#!/bin/sh /etc/rc.common

START=01
STOP=98
PROG=/sbin/boot-play
USE_PROCD=1

stop_service() {
    killall $PROG
}

start_service() {

    [ "x$(get_sn_mac.sh pcba_test)" = "x1" ] && exit 0

    $PROG boot
}
